### ISSUE TITLE
Spotify Issue,

### ISSUE THREAD

**Issue by Mongstaen** [insaiyancvk/pymusicdl#21]
Unable to use option "Download from Spotify"

**To Reproduce**
. Select "download from Spotify"

**Expected behavior**
Get prompted for spotify playlist url

[logger.log](https://github.com/insaiyancvk/pymusicdl/files/7738988/logger.log)

**Comment by insaiyancvk** [comment]
@Mongstaen It's a problem related to Spotipy (one of the dependencies). Just make sure you have `urllib3>=1.26` and `requests>=2.25`

Here's how to do it:
* Uninstall existing urllib3 and requests using:
```
pip uninstall urllib3 requests
```
* Install urllib3>=1.26 and requests>=2.25 using:
```
pip install urllib3>=1.26 requests>=2.25
```

**Note:** Perform the above operations in command prompt
