### ISSUE TITLE
i dont know

### ISSUE THREAD

**Issue by gogomano** [insaiyancvk/pymusicdl#4]
![image](https://user-images.githubusercontent.com/86175364/122659922-57deb200-d185-11eb-879b-74d1a1878f4f.png)

**Comment by insaiyancvk** [comment]
Hey @gogomano,

It looks like there's something wrong with the path of FFMPEG. Can you check if "python/scripts" is added to your PATH? It's most likely because of that.

**Comment by gogomano** [comment]
> Hey @gogomano,
> 
> It looks like there's something wrong with the path of FFMPEG. Can you check if "python/scripts" is added to your PATH? It's most likely because of that.
> If you don't understand all these paths and stuff, you can contact me via telegram. I can look into the problem myself if you are fine with it.

i fix it  tnx
!!!
