### ISSUE TITLE
musicdl command doesn't work

### ISSUE THREAD

**Issue by Chapter62** [insaiyancvk/pymusicdl#5]
I followed everything from the video provided but the command 'musicdl' doesn't work at all.

I use windows 

downloaded everything needed but still not working helpp pls
![scrnshot](https://user-images.githubusercontent.com/86544396/123532926-8bd84b00-d722-11eb-873e-7f4f147e6636.png)

**Comment by insaiyancvk** [comment]
Hey @Chapter62,

I think the problem is with the path. Can you check if python39/scripts is added to your path? 

The path would look like this ("Asus" would be your username instead):

![image](https://user-images.githubusercontent.com/53230977/123533063-12475980-d730-11eb-864a-3066de2d728d.png)

**Comment by Chapter62** [comment]
uhm?
![scrnshot1](https://user-images.githubusercontent.com/86544396/123533194-677d6e00-d724-11eb-8d7e-8735940762ea.png)

**Comment by Chapter62** [comment]
AAAAAAAAA got it i m dumb

i was using the administrator cmd the whole time 
thanks for your help tho

**Comment by insaiyancvk** [comment]
Oh, you solved the issue :)
Now spam downloads XD

**Comment by Chapter62** [comment]
> Oh, you solved the issue :)
> Now spam downloads XD

lol
