### ISSUE TITLE
dislike_count

### ISSUE THREAD

**Issue by Chapter62** [insaiyancvk/pymusicdl#7]
so i chose spotify in the menu on musicdl and pasted the link.. it fetched all details it needed but right after that this came about

![image](https://user-images.githubusercontent.com/86544396/126287439-1c8ec1ae-ca1a-4733-92d3-25958a8b58b0.png)

Also there is a problem where if one song in a playlist is not available the entire proccess stops
it kinda sucks but managable

**Comment by insaiyancvk** [comment]
Okay I've looked into it, and the dislike count thing is actually a problem related to "pafy" (a python library I used). I need to change the entire backend now :p
So if you go to that particular song in youtube, you should see the dislike count turned off. I think that's the problem.

And regarding the process stopping when there's an error, I can work on that and update. My classes have started so give me some time tho 😅

**Comment by Chapter62** [comment]
ohh ok
thank you

**Comment by insaiyancvk** [comment]
@Chapter62 can you share the playlist that you were trying to download? I'd like to test

**Comment by insaiyancvk** [comment]
> Also there is a problem where if one song in a playlist is not available the entire proccess stops
it kinda sucks but managable

@Chapter62 I updated the code. It skips the tracks that cause errors :)
Just update the package using `pip install pymusicdl -U`
